# Generated by Django 5.1.2 on 2024-10-17 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0002_remove_privatechat_user1_remove_privatechat_user2_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchat',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_group_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='privatechat',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_private_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='privatechat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_chats', to=settings.AUTH_USER_MODEL),
        ),
    ]
